import React from "react";



const shopProducts = [
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "man"},
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "man" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "woman"},
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "woman" },
    { name: "Black Tshirt", category: "Tshirt", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "woman" },
    { name: "Blue Jeans", category: "Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "man"},
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "man" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "woman"},
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "woman" },
    { name: "Blue Jeans", category: " Jeans", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "woman" },
    { name: "Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "kids"},
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "kids" },
    { name: " Kids Hat", category: "Hats", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "kids" },
    { name: " Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "men"},
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "men" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "woman"},
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "woman" },
    { name: "Love Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "woman" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "kids"},
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "kids" },
    { name: "Caillou Jackets", category: "Jackets", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "kids" },
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "woman" },
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "woman"},
    { name: "Charm Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "woman"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "man" },
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "man"},
    { name: "Car Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "man"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards1.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards2.jpg", gender: "kids" },
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards3.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards4.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards5.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards6.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards7.jpg", gender: "kids"},
    { name: "Birds Necklaces", category: "Jewellery", priceOld: "$16.48", priceNew: "$6.48", image: "/images/productcards8.jpg", gender: "kids"},
];
